/**
 * Deep Zoom Image (DZI) pyramids in the media library.
 *
 * A pyramid is a directory of many small tiles, which the flat media library (one file per
 * record, random names) cannot express, so it has its own flow — all role ≥ curator:
 *
 *   POST /api/admin/media/deepzoom            { name, width, height, tileSize?, overlap?, format? }
 *                                             → { set, base, tiles, directUpload }  (reserves a set id)
 *   POST /api/admin/media/deepzoom/tile?set=&path=image_files/<l>/<c>_<r>.jpg
 *                                             raw tile bytes (≤ 8 MB) → { ok, size }   (disk / small S3)
 *   POST /api/admin/media/deepzoom/presign    { set, paths[] ≤ 500 } → { uploads: [{ path, uploadUrl, method, headers }] }
 *                                             (S3 only: the browser PUTs tiles straight to the bucket)
 *   POST /api/admin/media/deepzoom/complete   { set, filename, width, height, tileSize, overlap, format, bytes }
 *                                             → verifies the corner tiles, writes `image.dzi`, records ONE
 *                                             media row (folder `deepzoom`) → 201 MediaRecord (url = the .dzi)
 *
 * Storage keys: `deepzoom/<set>/image.dzi` and `deepzoom/<set>/image_files/<level>/<col>_<row>.<ext>`.
 * The .dzi descriptor is always generated by the server (never uploaded), so no client XML is served.
 * Deleting the media record (DELETE /api/admin/media/:id) removes the whole pyramid.
 */
import 'server-only'
import { randomBytes, randomUUID } from 'node:crypto'
import fs from 'node:fs'
import { Readable, Transform } from 'node:stream'
import type { ReadableStream as NodeWebReadableStream } from 'node:stream/web'
import { DeleteObjectsCommand } from '@aws-sdk/client-s3'
import { dziLevelTiles, dziMaxLevel, dziTileCount, dziTilePath, dziXml, parseDzi, type DziInfo } from '../../museum/deepzoom/dzi'
import { config } from '../config'
import { nowIso } from '../db'
import { route } from '../http'
import type { LocalDiskStorage, S3Storage, StorageDriver } from '../storage'
import { fail, HttpError, isRecord } from '../util'

export const DEEPZOOM_FOLDER = 'deepzoom'
export const DZI_MIME = 'application/xml'
const MAX_TILE_BYTES = 8 * 1024 * 1024
const MAX_SIDE = 200_000
const MAX_TILES = 250_000
const SET_RE = /^[a-z0-9-]{1,60}-[0-9a-f]{8}$/
const TILE_RE = /^image_files\/(\d{1,2})\/(\d{1,5})_(\d{1,5})\.(jpg|jpeg|png|webp)$/
const TILE_MIME: Record<string, string> = { jpg: 'image/jpeg', jpeg: 'image/jpeg', png: 'image/png', webp: 'image/webp' }
/** Every key of a pyramid (for serving + the S3 redirect allow-list). */
export const DEEPZOOM_KEY_RE = /^deepzoom\/([a-z0-9-]{1,60}-[0-9a-f]{8})\/(image\.dzi|image_files\/\d{1,2}\/\d{1,5}_\d{1,5}\.(?:jpg|jpeg|png|webp))$/

export const isDeepZoomKey = (key: string) => DEEPZOOM_KEY_RE.test(key)
export const deepZoomDziKey = (set: string) => `${DEEPZOOM_FOLDER}/${set}/image.dzi`

function slug(name: string) {
  return (
    name
      .replace(/\.[a-z0-9]{2,5}$/i, '')
      .normalize('NFKD')
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 50) || 'image'
  )
}

function readSet(v: unknown): string {
  if (typeof v !== 'string' || !SET_RE.test(v)) return fail(400, 'Invalid "set"')
  return v
}

function readInfo(b: Record<string, unknown>): DziInfo {
  const width = Number(b.width)
  const height = Number(b.height)
  const tileSize = b.tileSize === undefined ? 254 : Number(b.tileSize)
  const overlap = b.overlap === undefined ? 1 : Number(b.overlap)
  const format = (b.format === undefined ? 'jpg' : String(b.format).toLowerCase()) as DziInfo['format']
  const int = (n: number) => Number.isInteger(n)
  if (!int(width) || !int(height) || width < 1 || height < 1 || width > MAX_SIDE || height > MAX_SIDE) fail(400, '"width"/"height" must be integers 1…200000')
  if (!int(tileSize) || tileSize < 64 || tileSize > 2048) fail(400, '"tileSize" must be 64…2048')
  if (!int(overlap) || overlap < 0 || overlap > 8) fail(400, '"overlap" must be 0…8')
  if (!TILE_MIME[format]) fail(400, '"format" must be jpg, png or webp')
  const info = { width, height, tileSize, overlap, format }
  if (dziTileCount(info) > MAX_TILES) fail(413, `Pyramid too large (max ${MAX_TILES} tiles)`)
  return info
}

function tileKey(set: string, rel: unknown) {
  if (typeof rel !== 'string') return fail(400, 'Invalid tile "path"')
  const m = TILE_RE.exec(rel)
  if (!m) return fail(400, 'Tile path must be image_files/<level>/<col>_<row>.<jpg|png|webp>')
  return { key: `${DEEPZOOM_FOLDER}/${set}/${rel}`, mime: TILE_MIME[m[4]] }
}

/** POST /api/admin/media/deepzoom — reserve a pyramid id. */
export const startDeepZoom = route(async (c) => {
  await c.requireCurator()
  const b = await c.json()
  if (!isRecord(b)) return fail(400, 'Body must be { name, width, height, tileSize?, overlap?, format? }')
  const info = readInfo(b)
  if (config.isVercel && c.storage.kind === 'local') return fail(501, 'Local disk storage is not available on Vercel; configure S3_BUCKET')
  const set = `${slug(typeof b.name === 'string' ? b.name : 'image')}-${randomBytes(4).toString('hex')}`
  c.status = 201
  return {
    set,
    base: c.storage.urlFor(`${DEEPZOOM_FOLDER}/${set}`),
    tiles: dziTileCount(info),
    maxLevel: dziMaxLevel(info.width, info.height),
    directUpload: typeof c.storage.presignPut === 'function',
    maxTileBytes: MAX_TILE_BYTES,
  }
})

/** POST /api/admin/media/deepzoom/tile?set=&path= — raw tile body (streams to storage). */
export const uploadDeepZoomTile = route(async (c) => {
  await c.requireCurator()
  const set = readSet(c.url.searchParams.get('set'))
  const { key, mime } = tileKey(set, c.url.searchParams.get('path'))
  if (!c.req.body) return fail(400, 'Empty body')
  const declared = Number(c.req.headers.get('content-length') ?? 0)
  if (declared > MAX_TILE_BYTES) return fail(413, 'Tile too large (max 8 MB)')
  let seen = 0
  const limiter = new Transform({
    transform(chunk: Buffer, _enc, cb) {
      seen += chunk.length
      if (seen > MAX_TILE_BYTES) cb(new HttpError(413, 'Tile too large (max 8 MB)'))
      else cb(null, chunk)
    },
  })
  const body = Readable.fromWeb(c.req.body as unknown as NodeWebReadableStream)
  body.on('error', (e) => limiter.destroy(e))
  // retries overwrite (the local driver refuses to clobber, so clear first)
  if (c.storage.kind === 'local') await c.storage.remove(key).catch(() => undefined)
  try {
    const saved = await c.storage.save(key, body.pipe(limiter), mime)
    if (saved.size === 0) {
      await c.storage.remove(key).catch(() => undefined)
      return fail(400, 'Empty tile')
    }
    return { ok: true, size: saved.size }
  } catch (err) {
    await c.storage.remove(key).catch(() => undefined)
    throw err
  }
})

/** POST /api/admin/media/deepzoom/presign — batch of presigned PUT URLs (S3). */
export const presignDeepZoom = route(async (c) => {
  await c.requireCurator()
  if (!c.storage.presignPut) return fail(501, 'Direct upload not supported by local storage; POST tiles to /api/admin/media/deepzoom/tile')
  const b = await c.json({ maxBytes: 256 * 1024 })
  if (!isRecord(b) || !Array.isArray(b.paths)) return fail(400, 'Body must be { set, paths: string[] }')
  const set = readSet(b.set)
  if (b.paths.length === 0 || b.paths.length > 500) return fail(400, '1…500 paths per request')
  const uploads = []
  for (const p of b.paths) {
    const { key, mime } = tileKey(set, p)
    uploads.push({ path: p as string, ...(await c.storage.presignPut(key, mime)) })
  }
  return { uploads }
})

/** POST /api/admin/media/deepzoom/complete — write image.dzi + record the pyramid. */
export const completeDeepZoom = route(async (c) => {
  await c.requireCurator()
  const b = await c.json()
  if (!isRecord(b)) return fail(400, 'Body must be { set, filename, width, height, tileSize, overlap, format, bytes }')
  const set = readSet(b.set)
  const info = readInfo(b)
  const storedName = `${set}/image.dzi`
  if (await c.db.one('SELECT id FROM media WHERE folder = $1 AND stored_name = $2', [DEEPZOOM_FOLDER, storedName])) return fail(409, 'Already recorded')
  // corner tiles of the top and bottom levels must exist
  const max = dziMaxLevel(info.width, info.height)
  const top = dziLevelTiles(info, max)
  const probes = [dziTilePath(info, 0, 0, 0), dziTilePath(info, max, 0, 0), dziTilePath(info, max, top[top.length - 1].col, top[top.length - 1].row)]
  for (const p of probes) {
    if (!(await c.storage.stat(`${DEEPZOOM_FOLDER}/${set}/${p}`))) return fail(400, `Tile ${p} is missing; upload every tile before completing`)
  }
  const xml = dziXml(info)
  await c.storage.save(deepZoomDziKey(set), Readable.from([Buffer.from(xml, 'utf8')]), DZI_MIME)
  const bytes = Number(b.bytes)
  const size = Number.isFinite(bytes) && bytes > 0 ? Math.round(bytes) : xml.length
  const filename = (typeof b.filename === 'string' && b.filename ? b.filename : `${set}.dzi`).slice(0, 255)
  const row = { id: randomUUID(), folder: DEEPZOOM_FOLDER, stored_name: storedName, filename, mime: DZI_MIME, size, created_at: nowIso() }
  await c.db.run('INSERT INTO media (id, folder, stored_name, filename, mime, size, created_at) VALUES ($1, $2, $3, $4, $5, $6, $7)', [
    row.id,
    row.folder,
    row.stored_name,
    row.filename,
    row.mime,
    row.size,
    row.created_at,
  ])
  c.status = 201
  return { id: row.id, url: c.storage.urlFor(deepZoomDziKey(set)), filename: row.filename, folder: row.folder, mime: row.mime, size: row.size, createdAt: row.created_at }
})

/** Remove a whole pyramid (called by DELETE /api/admin/media/:id for `deepzoom` rows). */
export async function removeDeepZoomSet(storage: StorageDriver, storedName: string) {
  const set = storedName.split('/')[0]
  if (!SET_RE.test(set)) return
  if (storage.kind === 'local') {
    const dir = (storage as LocalDiskStorage).filePath(`${DEEPZOOM_FOLDER}/${set}`)
    await fs.promises.rm(dir, { recursive: true, force: true })
    return
  }
  // S3: enumerate the tile keys from the descriptor (no ListBucket permission needed)
  const s3 = storage as S3Storage
  const keys = [deepZoomDziKey(set)]
  try {
    const res = await fetch(storage.urlFor(deepZoomDziKey(set)))
    const info = res.ok ? parseDzi(await res.text()) : null
    if (info) {
      for (let l = 0; l <= dziMaxLevel(info.width, info.height); l++) {
        for (const t of dziLevelTiles(info, l)) keys.push(`${DEEPZOOM_FOLDER}/${set}/${dziTilePath(info, l, t.col, t.row)}`)
      }
    }
  } catch (err) {
    console.warn('[museum] deep zoom: could not read descriptor for cleanup', err)
  }
  for (let i = 0; i < keys.length; i += 1000) {
    const chunk = keys.slice(i, i + 1000)
    await s3.client.send(
      new DeleteObjectsCommand({ Bucket: s3.bucket, Delete: { Objects: chunk.map((k) => ({ Key: s3.prefix + k })), Quiet: true } }),
    )
  }
}
